version: '3.6'
services:
  deeplinks-docker:
    image: menzorg/deeplinks:main
    networks:
      - network
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts: ['host.docker.internal:host-gateway']
    ports:
      - 3006:3006
    restart: always
    environment:
      DEEPLINKS_HASURA_PATH: '${DEEPLINKS_HASURA_PATH}'
      DEEPLINKS_HASURA_SSL: '${DEEPLINKS_HASURA_SSL}'
      DEEPLINKS_HASURA_SECRET: '${DEEPLINKS_HASURA_SECRET}'
      JWT_SECRET: '${JWT_SECRET}'
networks:
  network:
    driver: bridge
